### ISSUE TITLE
Container Port closed

### ISSUE THREAD

**Issue by sidneydemoraes** [jnovack/autossh#26]
I am able to setup the tunnel correctly as you can see below:
![image](https://user-images.githubusercontent.com/696278/97459996-1c078b80-191b-11eb-8613-c154a241349e.png)

However, when I try to reach it from another container within the same docker-compose project, that door is closed, as you can see below:
![image](https://user-images.githubusercontent.com/696278/97461073-25ddbe80-191c-11eb-801f-45aef2fb3d7b.png)

I setup autossh in my `docker-compose.yml` file like this:
![image](https://user-images.githubusercontent.com/696278/97460500-90dac580-191b-11eb-94e9-1ec32350a641.png)

What am I missing?

**Comment by sidneydemoraes** [comment]
Just found out that it's not working as stated on Docker's documentation.
Instead of using the service name as host (in my case, `autossh`) I had to connect to `0.0.0.0`.
Is that caused by some configuration on Alpine's image?
Have you seen this before?

**Comment by jnovack** [comment]
As you are quite aware, `127.0.0.0/8` is localhost. But what is important to understand about that is it's a NON-NETWORK localhost.  It doesn't mean "me", it means "me without external networking".

So when you say "me without external networking", nobody external can connect.  

`127.0.0.0/8` FAKES "me".  It is not ACTUALLY mean "me".

Always use `0.0.0.0` in docker containers.
