### ISSUE TITLE
Unnecessary SSH_BIND_IP warning

### ISSUE THREAD

**Issue by llamafilm** [jnovack/autossh#29]
Every time I start up, the log shows a scary warning:

```
[WARN ] SSH_BIND_IP requires additional server configuration to work properly
```

Since I am using `SSH_MODE=-L` I think there is no need for the warning.

**Comment by jnovack** [comment]
You are probably right.

https://github.com/jnovack/autossh/blob/432d3087f1ea33a4f312679637a3834b0546abc5/rootfs/entrypoint.sh#L34

Line 34 should most likely check for `-R`.
