### ISSUE TITLE
Randomized Port

### ISSUE THREAD

**Issue by SeanBaldacchino-HandsOn** [jnovack/autossh#48]
Apologies but this is more of a question than an issue.

We intend on utilising this for a specific use case where we have to use randomised ports.

You stated that if the value of SSH_TUNNEL_PORT is not set, a random port above 32768 will be chosen.

So my question is, what would be the behaviour if the random port that's chosen is a port that is already in use by another ssh tunnel? Would it crash and restart (therefore randomising the port again) ? Would it just fail to connect and not restart ?

**Comment by jnovack** [comment]
The operating system (the one running docker) picks a *FREE* port.  It would be silly to pick a port already in use, wouldn't it?
